# Generated by Django 5.2.17 on 2026-09-08 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=150, verbose_name="Họ tên khách thuê"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[0-9 ()-]{8,20}$",
                                (
                                    "Số điện thoại gồm 8–20 ký tự số, +, "
                                    "dấu cách hoặc dấu gạch."
                                ),
                            )
                        ],
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "identity_number",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{12}$", "CCCD cần đúng 12 chữ số."
                            )
                        ],
                        verbose_name="Số CCCD",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255, verbose_name="Địa chỉ thường trú"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=150, verbose_name="Họ tên người liên hệ"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        max_length=100, verbose_name="Mối quan hệ"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[0-9 ()-]{8,20}$",
                                (
                                    "Số điện thoại gồm 8–20 ký tự số, +, "
                                    "dấu cách hoặc dấu gạch."
                                ),
                            )
                        ],
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="tenants.tenant",
                        verbose_name="Khách thuê",
                    ),
                ),
            ],
        ),
    ]
