# Generated by Django 5.2.17 on 2026-09-08 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Mã hợp đồng"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu")),
                ("end_date", models.DateField(verbose_name="Ngày kết thúc")),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name="Tiền cọc (đ)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("active", "Đã ký"),
                            ("terminated", "Đã thanh lý"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "contract_content",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Dùng làm nguồn cho AI tóm tắt. Không"
                            " cần nhập CCCD, số điện thoại vào nộ"
                            "i dung này."
                        ),
                        max_length=100000,
                        verbose_name="Nội dung hợp đồng",
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="buildings.apartment",
                        verbose_name="Căn hộ",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="tenants.tenant",
                        verbose_name="Khách thuê",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__gt", models.F("start_date"))
                        ),
                        name="contract_valid_dates",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("deposit_amount__gte", 0)),
                        name="contract_nonnegative_deposit",
                    ),
                ],
            },
        ),
    ]
