# Generated by Django 5.2.17 on 2026-09-08 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        max_length=10000, verbose_name="Nội dung yêu cầu"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày tạo"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Thấp"),
                            ("normal", "Bình thường"),
                            ("high", "Khẩn cấp"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Mức độ ưu tiên",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Mới tiếp nhận"),
                            ("processing", "Đang xử lý"),
                            ("done", "Hoàn thành"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        max_length=10000,
                        verbose_name="Ghi chú xử lý",
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to="buildings.apartment",
                        verbose_name="Căn hộ",
                    ),
                ),
            ],
        ),
    ]
