# Generated by Django 5.2.17 on 2026-09-08 08:16

import django.db.models.deletion
import regulations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Tiêu đề quy định"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        max_length=100000, verbose_name="Nội dung quy định"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        max_length=100, verbose_name="Loại tài liệu"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lúc"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Đang áp dụng"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegulationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Tên tệp"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=regulations.models.document_path,
                        verbose_name="Tệp tài liệu",
                    ),
                ),
                (
                    "extracted_content",
                    models.TextField(
                        blank=True, verbose_name="Nội dung trích xuất"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày tạo"
                    ),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="regulations.regulation",
                        verbose_name="Quy định",
                    ),
                ),
            ],
        ),
    ]
