# Generated by Django 5.2.17 on 2026-09-08 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Số tiền (đ)",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rent", "Tiền thuê"),
                            ("service", "Phí dịch vụ"),
                        ],
                        max_length=20,
                        verbose_name="Loại khoản thu",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Hạn thanh toán")),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày thanh toán"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chưa thanh toán"),
                            ("paid", "Đã thanh toán"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="contracts.contract",
                        verbose_name="Hợp đồng",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="positive_payment_amount",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("paid_date__isnull", False),
                                ("status", "paid"),
                            ),
                            models.Q(
                                ("paid_date__isnull", True),
                                ("status", "pending"),
                            ),
                            _connector="OR",
                        ),
                        name="consistent_payment_date",
                    ),
                    models.UniqueConstraint(
                        fields=("contract", "kind", "due_date"),
                        name="unique_contract_payment_due",
                    ),
                ],
            },
        ),
    ]
