# Generated by Django 5.2.17 on 2026-09-08 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Tên tiện ích",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Mô tả"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Đang sử dụng"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, verbose_name="Mã căn hộ"),
                ),
                (
                    "floor",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Tầng"
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Diện tích (m²)",
                    ),
                ),
                (
                    "rent",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name="Giá thuê (đ/tháng)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Sẵn sàng cho thuê"),
                            ("maintenance", "Đang bảo trì"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Trạng thái vận hành",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Tên tòa nhà"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Địa chỉ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Mô tả"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Đang hoạt động"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApartmentAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Số lượng",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ghi chú"
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="buildings.amenity",
                        verbose_name="Tiện ích",
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_links",
                        to="buildings.apartment",
                        verbose_name="Căn hộ",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="apartment",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                through="buildings.ApartmentAmenity",
                to="buildings.amenity",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apartments",
                to="buildings.building",
                verbose_name="Tòa nhà",
            ),
        ),
        migrations.AddConstraint(
            model_name="apartmentamenity",
            constraint=models.UniqueConstraint(
                fields=("apartment", "amenity"),
                name="unique_apartment_amenity",
            ),
        ),
        migrations.AddConstraint(
            model_name="apartmentamenity",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="positive_amenity_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="apartment",
            constraint=models.UniqueConstraint(
                fields=("building", "code"),
                name="unique_apartment_code_in_building",
            ),
        ),
        migrations.AddConstraint(
            model_name="apartment",
            constraint=models.CheckConstraint(
                condition=models.Q(("rent__gte", 0), ("area__gt", 0)),
                name="valid_apartment_amounts",
            ),
        ),
    ]
